AppBundle\Entity\Member:
  properties:
    firstName:
    - NotBlank: ~
    lastName:
    - NotBlank: ~
    email:
    - NotBlank: ~
    - Email:
        message: The email "{{ value }}" is not a valid email.
  constraints:
  - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email